
CREATE SEQUENCE public."Keys_Id_seq"
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public."Users_Id_seq";

CREATE SEQUENCE public."Users_Id_seq"
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;-- public."Keys" definition

-- Drop table

-- DROP TABLE public."Keys";

CREATE TABLE public."Keys" (
	"Id" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"KeyIdentifier" varchar(50) NOT NULL,
	CONSTRAINT "PK_Keys" PRIMARY KEY ("Id")
);
CREATE UNIQUE INDEX "IX_Keys_KeyIdentifier" ON public."Keys" USING btree ("KeyIdentifier");


-- public."Users" definition

-- Drop table

-- DROP TABLE public."Users";

CREATE TABLE public."Users" (
	"Id" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"FirstName" varchar(50) NOT NULL,
	"LastName" varchar(50) NOT NULL,
	"SSN" int8 NULL,
	CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);


-- public."UserAddresses" definition

-- Drop table

-- DROP TABLE public."UserAddresses";

CREATE TABLE public."UserAddresses" (
	"Id" int4 NOT NULL,
	"LeaseStart" timestamptz NOT NULL,
	"LeaseEnd" timestamptz NULL,
	"Address" varchar(50) NOT NULL,
	CONSTRAINT "PK_UserAddresses" PRIMARY KEY ("Id"),
	CONSTRAINT "FK_UserAddresses_Keys_Id" FOREIGN KEY ("Id") REFERENCES public."Keys"("Id") ON DELETE CASCADE,
	CONSTRAINT "FK_UserAddresses_Users_Id" FOREIGN KEY ("Id") REFERENCES public."Users"("Id") ON DELETE CASCADE
);


-- Insert dummy users
INSERT INTO users (first_name, last_name, ssn) VALUES
('John', 'Doe', 123456789),
('Jane', 'Smith', 987654321),
('Alice', 'Johnson', 555443322),
('Bob', 'Brown', 112233445),
('Charlie', 'Davis', 667788990);

-- Insert dummy keys
INSERT INTO keys (key_identifier) VALUES
('KEY-12345'),
('KEY-67890'),
('KEY-ABCDE'),
('KEY-FGHIJ'),
('KEY-KLMNO');

-- Insert dummy user addresses
INSERT INTO userAddress (id, lease_start, lease_end, userAdress) VALUES
(1, '2023-01-01 12:00:00', '2024-01-01 12:00:00', '123 Main St, Cityville'),
(2, '2022-05-15 10:00:00', '2023-05-15 10:00:00', '456 Elm St, Townburg'),
(3, '2021-07-20 08:30:00', '2022-07-20 08:30:00', '789 Oak St, Villageton'),
(4, '2024-02-01 14:45:00', NULL, '101 Pine St, Hamletown'),
(5, '2023-09-10 16:00:00', '2025-09-10 16:00:00', '202 Birch St, Countryside');