// <auto-generated />
using System;
using KeyManager.Persistence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KeyManager.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260317184101_nullableRelations")]
    partial class nullableRelations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KeyManager.Domain.Models.Key", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Brand")
                        .HasColumnType("integer");

                    b.Property<bool>("IsLost")
                        .HasColumnType("boolean");

                    b.Property<string>("KeyIdentifier")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("PropertyId")
                        .HasColumnType("integer");

                    b.Property<int?>("ResidentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.HasIndex("ResidentId");

                    b.ToTable("Keys");
                });

            modelBuilder.Entity("KeyManager.Domain.Models.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("LeaseEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LeaseStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ResidentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ResidentId");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("KeyManager.Domain.Models.Resident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long?>("Pnum")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Residents");
                });

            modelBuilder.Entity("KeyManager.Domain.Models.Key", b =>
                {
                    b.HasOne("KeyManager.Domain.Models.Property", "Property")
                        .WithMany("Keys")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("KeyManager.Domain.Models.Resident", "Resident")
                        .WithMany("Keys")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Property");

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("KeyManager.Domain.Models.Property", b =>
                {
                    b.HasOne("KeyManager.Domain.Models.Resident", "Resident")
                        .WithMany("Properties")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("KeyManager.Domain.Models.Property", b =>
                {
                    b.Navigation("Keys");
                });

            modelBuilder.Entity("KeyManager.Domain.Models.Resident", b =>
                {
                    b.Navigation("Keys");

                    b.Navigation("Properties");
                });
#pragma warning restore 612, 618
        }
    }
}
